### ISSUE TITLE
have.prop checks on reference not equality

### ISSUE THREAD

**Issue by marcodejongh** [producthunt/chai-enzyme#10]
have.prop should check on object equality not reference equality.

When using immutable it becomes next to impossible to use reference equality because the object where it was set will be different where it is used.

**Comment by ljharb** [comment]
when using immutable, it seems like using immutable's comparison functions are always the right way to go about it.

**Comment by marcodejongh** [comment]
@ljharb Well not necessarily you could be passing the ```.get``` value of your immutable store to a child component, in which case you want to be able to assert on object equality and not reference equality.

You won't be able to use immutable comparisons because the ```.get``` would return a raw object

**Comment by ljharb** [comment]
ah, gotcha.

there's `deepEqual`, or the `is-equal` module - would those work?

**Comment by marcodejongh** [comment]
Yes that would work, but It's probably also possible to just use the deep equal built into chai (```to.eql``` or ```to.deep.equal```)

This would be for the whole generic assertion https://github.com/producthunt/chai-enzyme/blob/master/src/assertions/generic.js#L6

So it would affect all the assertions here:
https://github.com/producthunt/chai-enzyme/blob/master/src/index.js#L74-L78

**Comment by ljharb** [comment]
We should be able to make `.to.have.deep.prop` work?

**Comment by vesln** [comment]
agree, we can easily implement `to.have.deep.prop`

**Comment by vesln** [comment]
https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L518-L528

https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L484

**Comment by marcodejongh** [comment]
@vesln This actually doesn't need something extra added as I can just use:

```
expect(wrapper.find(User).first()).to.have.prop('objectProp').deep.equal({foo: 'bar'})
```

So I guess this can be closed as "won't fix"
