### ISSUE TITLE
TypeError: not a function

### ISSUE THREAD

**Issue by AlexEscalante** [producthunt/chai-enzyme#103]
Hello, guys. I was told [here](https://github.com/chaijs/chai/issues/777) to use chai-enzyme to get the `to.exist` assertion working. Currently it just gives false positives, which is terrible, I think. I am just pasting here the last comment since it got not attention there:

I tried using chai-enzyme but had no luck:

    import chai, {expect} from 'chai';
    import chaiEnzyme from 'chai-enzyme';

    chai.use(chaiEnzyme());

With that setup, every time I get a wrapper:

    const wrapper = shallow(<ReceiptPage {...props} />);

... I get an error:

     TypeError: (0 , _enzyme2.default) is not a function

These are the versions I am using:

    "chai": "3.5.0",
    "chai-enzyme": "0.5.1",
    "enzyme": "2.2.0",
    "cheerio": "0.20.0",
    "react": "15.0.2"

**Comment by ayrton** [comment]
Can you cross reference if you setup chai-enzyme any different that [the repo](https://github.com/ayrton/chai-enzyme-issue-92) I created for #92  please.

**Comment by AlexEscalante** [comment]
This is odd. I tried to integrate chai-enzyme again and I could not reproduce my issue. Sorry, I am closing this.
