### ISSUE TITLE
Why does tagName assertion delegate to the name property on shallow/cheerio wrapper?

### ISSUE THREAD

**Issue by prurph** [producthunt/chai-enzyme#107]
I'm a bit confused by the implementations of `tagName` on some of the wrappers where they delegate to the element's `name` property: https://github.com/producthunt/chai-enzyme/blob/master/src/ShallowTestWrapper.js#L44.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/name) the name property only exists for certain elements. Why do the shallow and cheerio wrappers not use `tagName`? I have failing assertions assertions like: 

```es6
class MySpanComponent extends React.Component {
  render() {
    return (<span />);
  }
}

// Fails because .name is undefined; .tagName is the expected "SPAN"
expect(shallow(<MySpanComponent />)).to.have.tagName('span')
```

Is this an issue with chai-enzyme or am I doing something wrong/missing something? Thanks!

**Comment by ayrton** [comment]
I can't remember what the exact reason was to use `name` when I added the tagName matcher in https://github.com/producthunt/chai-enzyme/commit/c5b435bfc7a8625dc3e33e3fe926b9d359d7b456. I don't see anything wrong with your code, so this is most likely a bug. Feel free to open a PR to update the implementation, but please make sure that existing tests succeed and add a new test (that fails with the current code) to test the scenario above.

**Comment by prurph** [comment]
Thanks for the quick response! Having forked the repo I'm unable to replicate my failures, so while it seems like in theory these should be calling `tagName` (and the existing tests here do pass with this change), it must be something with the environment for the project where I'm having the issue.  Perhaps a weird dependency mismatch causing `$(this.wrapper.html())` to return something without a `name` property whereas in the proper setup this is not the case.

I'll keep tinkering with it but since I can't seem to write a failing test in the chai-enzyme suite itself it seems reckless to change `name` to `tagName` in the implementations. Feel free to close this.

**Comment by prurph** [comment]
Just an update to this in case someone else stumbles across this. I upgraded to cheerio 0.22 from 0.19 and the issue went away. It surfaced in the first place upon upgrading lodash from 3.x to 4.x and some weird interactions related to that whole change since we do make `_` available globally.
