### ISSUE TITLE
contain text assertion does not work if String.prototype.includes is not available

### ISSUE THREAD

**Issue by rincedd** [producthunt/chai-enzyme#116]
The following breaks in environments that do not support the ES2015 method `String.prototype.includes`, such as Internet Explorer and Phantom JS.
```js
expect(wrapper.find('#child')).to.contain.text('Te')
```
I guess the solution would be to include an appropriate polyfill in the build.

**Comment by ayrton** [comment]
Closely related to https://github.com/producthunt/chai-enzyme/pull/111

**Comment by ayrton** [comment]
Merged in #111 so this will no longer be an issue on the next release

**Comment by rincedd** [comment]
Thanks :+1:
