### ISSUE TITLE
Can't run on react-addons-test-utils@15.4.0-rc.3

### ISSUE THREAD

**Issue by wellyshen** [producthunt/chai-enzyme#117]
Hi I update my react, react-dom, react-addons-test-utils to 15.4.0-rc.3, that the error occurs when I run `npm test`.

> ERROR in ./~/react-element-to-jsx-string/~/react-addons-test-utils/index.js
> Module not found: Error: Can't resolve 'react/lib/ReactTestUtils' in '/Users/Welly/Desktop/react-cool-starter/node_modules/react-element-to-jsx-string/node_modules/react-addons-test-utils'
>  @ ./~/react-element-to-jsx-string/~/react-addons-test-utils/index.js 1:17-52
>  @ ./~/react-element-to-jsx-string/index-dist.js
>  @ ./~/chai-enzyme/build/assertions/contain.js
>  @ ./~/chai-enzyme/build/index.js
>  @ ./tools/testing/test-bundler.js

Any solution for this?

**Comment by ayrton** [comment]
Our dependency was a little outdated, I've updated react-element-to-jsx-string to ^5.0.0 can you verify if this is still an issue with chai-enzyme 0.6.0 (to be released later today)

**Comment by ayrton** [comment]
Our dependency were a little outdated, I've updated react-element-to-jsx-string to ^5.0.0 can you verify if this is still an issue when using chai-enzyme@0.6.0?

**Comment by wellyshen** [comment]
Hi @ayrton, I have tried to upgrade the chai-enzyme to v0.6.0 but I still get the error :

>ERROR in ./~/react-element-to-jsx-string/~/react-addons-test-utils/index.js
Module not found: Error: Can't resolve 'react/lib/ReactTestUtils' in '/Users/Welly/Desktop/react-cool-starter/node_modules/react-element-to-jsx-string/node_modules/react-addons-test-utils'
 @ ./~/react-element-to-jsx-string/~/react-addons-test-utils/index.js 1:17-52
 @ ./~/react-element-to-jsx-string/index-dist.js
 @ ./~/chai-enzyme/build/assertions/contain.js
 @ ./~/chai-enzyme/build/index.js
 @ ./tools/testing/test-bundler.js

**Comment by ayrton** [comment]
I think there's something seriously wrong with the following path:

```
/Users/Welly/Desktop/react-cool-starter/node_modules/react-element-to-jsx-string/node_modules/react-addons-test-utils
```

react-addons-test-utils should live in:

```
/Users/Welly/Desktop/react-cool-starter/node_modules/react-addons-test-utils
```

Not in the above.

**Comment by wellyshen** [comment]
@ayrton The react-addons-test-utils was installed in the path of node_modules, you can see my [repo](https://github.com/wellyshen/react-cool-starter/blob/master/package.json). I rollback to 15.3.2 due to this issue.

**Comment by ayrton** [comment]
I have the feeling this is an issue with [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) using react internals (which have changed in the rc version). Can you create an issue there and see if they know more?

**Comment by wellyshen** [comment]
@ayrton OK, thanks.

**Comment by ljharb** [comment]
react-addons-test-utils should not be a dependency of anything - only a peer dep - just like react and react-dom - this is how singletons work in the npm ecosystem.

Thus, react-addons-test-utils should never exist anywhere but in your package.json, in the peerDeps of related modules, and in the top level of your `node_modules`. If react-element-jsx-to-string violates this, it's a bug in that package.
