### ISSUE TITLE
Tests fail with Enzyme 2.5.0

### ISSUE THREAD

**Issue by imakewebthings** [producthunt/chai-enzyme#119]
Enzyme 2.5.0 was released 12 hours ago. With that version, `.to.have.attr` (and probably other) calls are failing with an error of `cannot read property "call" of undefined`.

Running chia-enzyme tests with enzyme@2.4.1, all 373 tests pass.

Running chai-enzyme tests with enzyme@2.5.0, 312 passing, 61 failing.

**Comment by ayrton** [comment]
The maintainers of enzyme are on it, this will be fixed in the next release of Enzyme. See #118 for more information

**Comment by imakewebthings** [comment]
@ayrton Ah, my bad, I should have checked PRs first. Thank you for the fast response and keep up the excellent work.

**Comment by ayrton** [comment]
@imakewebthings you can now upgrade to enzyme@2.5.1
