### ISSUE TITLE
Lastest React 15.4.0 breaks running test

### ISSUE THREAD

**Issue by arnaudlimbourg** [producthunt/chai-enzyme#129]
The latest React release moved the last remnants of dom related code to react-dom.

Running chai-enzyme breaks with the following error
```
Error: Cannot find module 'react/lib/ReactTestUtils'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (./node_modules/chai-enzyme/node_modules/react-addons-test-utils/index.js:1:-44)
```

Changing the incriminated line to
` module.exports = require('react-dom/lib/ReactTestUtils');`

makes it work but it might have other implications.

refs #https://github.com/facebook/react/issues/8314

**Comment by ljharb** [comment]
`react-addons-test-utils` should be both a devDependency and a peerDependency of `chai-enzyme`, and like `react` and `react-dom` (which should also be peerDeps + devDeps), should match your react version.

If all three are on 15.4, you won't have a problem.

**Comment by ayrton** [comment]
@ljharb do you recommend pinning react-addons-test-utils, react & react-dom in both devDependencies & peerDependencies to `^15.4.0-0` and releasing a new chai-enzyme version?

More context: https://github.com/algolia/react-element-to-jsx-string/issues/56

**Comment by ljharb** [comment]
@ayrton Separate from the react-element-to-jsx-string issue, I'd say that all three of those libs should have as wide a semver range in peerDeps as possible (ideally allowing ^0.14 - ^15), and a compatible ^ range in devDeps (all three the same). I don't think it needs to be pinned; and RC versions shouldn't be that much of a concern, but if the semver range can include it, more the better.

**Comment by vvo** [comment]
As for react-element-to-jsx-string, this is now fixed on our side.

**Comment by ayrton** [comment]
@ljharb confirmed in #130 that this fixes the issue above
@vvo thanks

Will release a new version soon.
