### ISSUE TITLE
exactly(0).descendants does not work as expected

### ISSUE THREAD

**Issue by lukebatchelor** [producthunt/chai-enzyme#141]
There's a strange edge case in `exactly` where searching for `exactly(0)` descendants will always return true.

I've only had a **very** brief look I'm guessing it's to do with this [file](https://github.com/producthunt/chai-enzyme/blob/master/src/chains/exactly.js)

where it sets the `exactlyCount` flag. I'm thinking this is being set to 0 then interpreted as a boolean false somewhere, so that when it get's checked [here](https://github.com/producthunt/chai-enzyme/blob/master/src/assertions/descendants.js#L4) it is going down the non-exact-count code path.

I'll try to get some time to make a PR for this soon if you like.

Cheers

**Comment by ayrton** [comment]
I believe this is now fixed as of #152
