### ISSUE TITLE
containMatchingElement not defined

### ISSUE THREAD

**Issue by mir3z** [producthunt/chai-enzyme#150]
Documentation described undefined method: `containMatchingElement`. I can't see this method in exports nor in whole codebase.

```
TypeError: (0 , _chai.expect)(...).to.containMatchingElement is not a function
```

**Comment by ayrton** [comment]
This feature currently hasn't been shipped yet, you'll have to wait until we cut a new release

**Comment by lucasmotta** [comment]
@ayrton any estimate of when it will be shipped?

cheers :)

**Comment by ayrton** [comment]
@lucasmotta will try to release this week, if I haven't yet, feel free to ping me again. If you'd like to help feel free to open a PR with the updated changelog

**Comment by iangreenleaf** [comment]
Friendly ping 🛎

I'd love to see a new version with this as it'll make our tests way cleaner.

**Comment by broncha** [comment]
Ping!
I have been trying to write tests that contain matching element, but all fail due to differences in the rendering. Some render with whitespaces, some not.. which are all valid cases.

**Comment by broncha** [comment]
Anything on the new release with this fix? Apparantly npm does not build the package when installed though github!

**Comment by viniciusffj** [comment]
When will be this feature available? I really need it

**Comment by JoshuaKGoldberg** [comment]
FYI, this is in the `@types` definition for `chai-enzyme`. Good thing this issue gets ranked well on Google!

**Comment by ljharb** [comment]
@JoshuaKGoldberg then that's a bug in the definition :-)

**Comment by ayrton** [comment]
Shipped today!
