### ISSUE TITLE
How to get it working in Karma?

### ISSUE THREAD

**Issue by jbinto** [producthunt/chai-enzyme#16]
On https://github.com/mxstbr/react-boilerplate/issues/79#issuecomment-174238581 (see link for more info) we are trying to convert from mocha/jsdom to Karma/Chrome.

I tried to create a Karma plugin for `chai-enzyme` (a naive copy paste based on another `karma-chai-foobar`) but I'm having trouble with the fact that `chai-enzyme` is published as an ES6 module, [and Karma doesn't understand that](https://github.com/karma-runner/karma/blob/ecd8546ab1b51390d546abd03424b7a731a50ce5/lib/plugin.js#L15).

I admit I am pretty fuzzy when it comes to implementation details of `require`, CommonJS, ES modules, etc. I know even less about Karma plugins. 

How could we get this working?

**Comment by vesln** [comment]
@jbinto thanks for your work!

chai-enzyme is transpiled to es2015 with babel, so this shouldn't be the issue. 

i believe it's the fact that we are trying to run commonjs code in a browser environment without any preparation. both mocha and chai come with a browser bundle see https://github.com/xdissent/karma-chai/blob/master/index.js#L9

i believe we can use webpack to accomplish it see https://webpack.github.io/docs/configuration.html#output-librarytarget

this can be done either in this repository, a separate one or in your karma plugin.

let me know if you wanna try to tackle this... i'll be very happy to assist in any way possible

**Comment by ljharb** [comment]
(You can also use browserify)

**Comment by marr** [comment]
I am having trouble getting this working with browserify and tape. Unrelated to karma but it seems appropriate: 
```
$ browserify -t babelify test/components/my-component.spec.js
Error: Cannot find module 'react/lib/ReactContext' from '/Users/dm/src/my-boilerplate/node_modules/enzyme/build'
    at /Users/dm/src/my-boilerplate/node_modules/resolve/lib/async.js:46:17
    at process (/Users/dm/src/my-boilerplate/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/dm/src/my-boilerplate/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/dm/src/my-boilerplate/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/dm/src/my-boilerplate/node_modules/resolve/lib/async.js:92:31)
    at /Users/dm/src/my-boilerplate/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```
Here is a repo I am working on: https://github.com/marr/my-boilerplate

**Comment by marr** [comment]
FWIW, I did get this working in browser with tape, https://github.com/airbnb/enzyme/issues/132#issuecomment-174800141

**Comment by vesln** [comment]
good to know, thanks!

**Comment by ayrton** [comment]
@jbinto is it possible you can get it working by requiring like this:

```js 
var chai-enzyme = require('chai-enzyme').default

// vs.

var chai-enzyme = require('chai-enzyme')
```

This is something we will have to address soon, let me know if that fixes it for you if so I'll make some time to get this working out of the box. For future me see [`babel-plugin-add-module-exports`](https://www.npmjs.com/package/babel-plugin-add-module-exports).

**Comment by ljharb** [comment]
Actually a better solution would be for `chai-enzyme`'s main entry point to use `module.exports = theDefault` instead of `export default theDefault`. Consumers should **never** have to interact with babel's CommonJS interop.

**Comment by ayrton** [comment]
@jbinto this should be no longer an issue as of `v0.3.0`, feel free to re-open if you still have any problems.

**Comment by reintroducing** [comment]
I'm trying to get this working with a Karma/webpack setup and I'm pretty lost as to how to do this. What is the proper way to get this working with Karma? Is there documentation anywhere that would show this? Would really appreciate any help offered.

**Comment by ayrton** [comment]
@reintroducing I'm not familiar with karma, but I saw @jbinto figured this out in https://github.com/mxstbr/react-boilerplate/issues/119 & https://github.com/mxstbr/react-boilerplate/pull/150. Maybe checking out react-boilerplate's [karma.conf.js](https://github.com/mxstbr/react-boilerplate/blob/master/internals/testing/karma.conf.js) will help you out.

**Comment by reintroducing** [comment]
@ayrton I looked it over before posting but the setup is slightly different than mine. I'm going to try again with that exact setup when I get a moment and see if I can chase this down. Thanks for the links.
