### ISSUE TITLE
support chai-4

### ISSUE THREAD

**Issue by soenkehahn** [producthunt/chai-enzyme#187]
It seems currently only `chai-3.x` is supported. (https://github.com/producthunt/chai-enzyme/blob/master/package.json#L29) `chai-4` is the current stable release.

**Comment by ayrton** [comment]
Greenkeeper PR #184

**Comment by ayrton** [comment]
Fixed as of #188

**Comment by soenkehahn** [comment]
Awesome, thanks a lot. Will we get a release soon?

**Comment by layershifter** [comment]
Please release this.

**Comment by ayrton** [comment]
Released 0.8.0
