### ISSUE TITLE
Dependency issues with new version of enzyme

### ISSUE THREAD

**Issue by nemanjacosovic** [producthunt/chai-enzyme#211]
I'm using "enzyme": "^3.2.0" and today, after installing chai-enzyme I got:

> npm WARN chai-enzyme@0.8.0 requires a peer of enzyme@1.x || ^2.3.0 but none is installed. You must install peer dependencies yourself.

**Comment by ayrton** [comment]
See #199

**Comment by ayrton** [comment]
0.8.0 does not support enzyme 3, the issue I referenced is about support with enzyme 3 which you are on. You need the beta version of chai-enzyme, for more information check out the issue there. React 15 and more happens to require enzyme 3, so it's misleading.

**Comment by nemanjacosovic** [comment]
Ok, thanks.
