### ISSUE TITLE
React 15.0.0 and Enzyme 3.2.0 issue

### ISSUE THREAD

**Issue by nemanjacosovic** [producthunt/chai-enzyme#212]
I'm using "enzyme": "^3.2.0" and today, after installing chai-enzyme I got:

npm WARN chai-enzyme@0.8.0 requires a peer of enzyme@1.x || ^2.3.0 but none is installed. You must install peer dependencies yourself.

**Comment by nemanjacosovic** [comment]
After some digging around, and help from @ayrton I've installed beta version which solved the issue.

However, now I have a new one:

**Comment by ljharb** [comment]
Duplicate of #211.

**Comment by nemanjacosovic** [comment]
Solution is to install beta:

npm install --save-dev chai-enzyme@beta
