### ISSUE TITLE
Flow types

### ISSUE THREAD

**Issue by gugu** [producthunt/chai-enzyme#226]
Unfortunately, I don't have time to do this by myself, but it will be nice to have flow type definitions for this module

Currently, flow raises an error because chai does not have additional methods (instead of the default behavior of ignoring module)

**Comment by ljharb** [comment]
https://www.npmjs.com/package/@types/chai-enzyme exists; flow could be added here: https://github.com/flow-typed/flow-typed/tree/87f3b2251f175a68c0ea9ec47ef489eabaa44e6c/definitions/npm
