### ISSUE TITLE
Remove second argument from generic assertions(attr, data, style, state, prop)

### ISSUE THREAD

**Issue by marcodejongh** [producthunt/chai-enzyme#23]
I think we should remove the second argument from the generic assertions, because chaining should be the recommended use. Currently in the documentation the chaining possibility isn't really pushed even though it is much more powerful then using the second argument.

**Comment by ayrton** [comment]
I don't have strong feelings about this, but I _currently_ don't see the need to break backwards compatibility here, it's a matter of style. We could however do a better job to emphasise more on chaining in the docs if desirable.

**Comment by vesln** [comment]
i see where you are coming from, but when we designed the api, we wanted it to feel as close to [chai-jquery](https://github.com/chaijs/chai-jquery) and other chai.js plugins and removing this functionality is agains this ideology

happy to update the docs and add more examples of chained assertions, but this is def not going away at this point.
