### ISSUE TITLE
expect(undefined).to.have.className("WTF”); // this passes somehow?

### ISSUE THREAD

**Issue by annthurium** [producthunt/chai-enzyme#41]
It seems like asserting that undefined has a classname should fail, but it's passing.

**Comment by marcodejongh** [comment]
@annthurium Are you using the latest version? this should have been fixed with #11

**Comment by annthurium** [comment]
@marcodejongh I am not!  Will upgrade.  Sorry about that -- I'll check past issues before commenting next time.
