### ISSUE TITLE
assertion on value() doesn't work if valueLink is used

### ISSUE THREAD

**Issue by eyalw** [producthunt/chai-enzyme#45]
if I use
```javascript
<input type="text" value="hello" />
```
the assertion `should.have.value('hello')` will work, but if `valueLink` prop is provided with this value, the assertion will fail.

**Comment by ayrton** [comment]
@eyalw could you elaborate a little, preferably I'd have a working (or failing ;))  example where I can reproduce the issue so I can look into this.

**Comment by eyalw** [comment]
sure, 
so I use enzyme to `mount()` a tree of componenets including `<<input type="text" valueLink={...}" />`.
As you know, `valueLink` prop is an official React feature to pass down to inputs to bind them to state.
a valueLink is basically an object like so: `{ value: '...', requestChange: function(val) {...}}`.

What happens is that the chai-enzume assertion on value I guess checks for the value prop and ignores my valueLink prop

**Comment by ljharb** [comment]
Presumably this is when using shallow rendering?

`.should.have.value` definitely does (and should) only check the `value` prop. It's a prop assertion, not a "resulting value in the DOM" assertion.

I'd do an explicit assertion on the `valueLink` prop for the `shallow` case. I'd expect `mount` would actually result in a `value` prop, and `render` certainly should.

**Comment by eyalw** [comment]
I'm using enzyme `mount()`, not shallow rendering. I personally disagree
about the assertion only checking only the value prop, because valueLink
also gives a value prop... and it serves the same purpose exactly as the
regular value prop. I see no reason why it shouldn't check for both, what
do you think?

**Comment by ljharb** [comment]
That would make `valueLink` a very special case. I'd expect in both shallow and mount that you can only find props that *you literally typed in your code* - that React turns it into `value` is something `render()` would cover, but nothing else.

**Comment by eyalw** [comment]
I understand the inconsistency with shallowRendering,
but I also think that when you write value() you expect it to check the value of the input, not the actual prop you passed. it's more logical. otherwise you should check with .prop('value', ..)..

anyway, that's my 2 cents

**Comment by ljharb** [comment]
heads up - React v15 [officially deprecates](https://facebook.github.io/react/blog/#new-deprecations-introduced-with-a-warning) valueLink and it will be removed in v16, so I don't think it'd add value to add special support for it.

**Comment by ayrton** [comment]
I agree with @ljharb here, doesn't seem likely the enzyme or chai-enzyme team will add support for `valueLink` considering it is deprecated. 

Personally I have not used `valueLink` ever, but feel free to create a PR to add this functionality and we will consider pulling it in.
