### ISSUE TITLE
`attr` fails for falsey attribute values

### ISSUE THREAD

**Issue by keithamus** [producthunt/chai-enzyme#47]
Hey everyone, great work on the awesome chai plugin!

The `.attr()` assertion fails when asserting on an attribute with a falsey value, such as an empty string.

Consider the following html:

```html
<article itemscope itemtype="http://schema.org/Article" itemprop="article"></article>
```

Asserting `expect(article).to.have.attr('itemscope')` fails when using enzyme's `mount`. It fails because [ReactTestWrapper calls `getAttribute(name) || undefined`](https://github.com/producthunt/chai-enzyme/blob/master/src/ReactTestWrapper.js#L31-L33) - and the `itemscope`'s result from `getAttribute` is `''`.

It should be noted that (although I haven't actually tested) - I believe that the CheerioWrapper won't do the same ([it doesn't use `|| undefined` in the wrapper code](https://github.com/producthunt/chai-enzyme/blob/master/src/CheerioTestWrapper.js#L33-L35) and [Cheerio itself returns the property verbatum](https://github.com/cheeriojs/cheerio/blob/master/lib/api/attributes.js#L38-L41)). 

### Solution

Do not use `|| undefined`. Instead pass the attribute verbatim. `getAttribute` will return `null` for attributes which don't exist on the element, which can be used to accurately detect the lack of an attribute over falsey values.

**Comment by vesln** [comment]
@keithamus thanks for opening the issue and the detailed explanation! if you have time to fix the issue and submit a pr, that'd be epic, if not i can do it myself too, just lmk. btw i also granted you push access, which is a small way to say thanks

**Comment by tleunen** [comment]
Same issue, especially when testing input fields...
```
AssertionError: expected the node in <Checkbox /> to have a 'disabled' attribute     
     
     HTML:
     
     <input type="checkbox" disabled="">
```

**Comment by ljharb** [comment]
To clarify, `<a b />` should have an implicit value of `true` for the `b` prop on `a`.
