### ISSUE TITLE
containsMatchingElement

### ISSUE THREAD

**Issue by ayrton** [producthunt/chai-enzyme#85]
We should consider adding [loose equals and loose contain](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/containsMatchingElement.md) assertions, these were recently intro'd in [enzyme@2.3.0](https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md#230-may-9-2016), specifically in this [PR](https://github.com/airbnb/enzyme/pull/362).

**Comment by vesln** [comment]
sweet.

any suggestions about the dsl? `.loose.equal()` and `.loose.contain()` is one option

**Comment by LeopoldoFu** [comment]
Seems like it is [matchesElement](http://airbnb.io/enzyme/docs/api/ShallowWrapper/matchesElement.html) now.

**Comment by ayrton** [comment]
From reading the documentation

- `.loose.equal()` would need to use [`containsMatchingElement`](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/containsMatchingElement.md) 
- `.loose.contain()` would need to use [`matchesElement`](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/matchesElement.md)

@lelandrichardson @ljharb what are your thoughts on the `loose` for the dsl?

**Comment by ljharb** [comment]
Wouldn't it be the opposite? `loose.equal()` should be `matchesElement`, and `loose.contain` should be `containsMatchingElement`?

**Comment by ljharb** [comment]
It seems like it'd be simplier to do `expect(foo).to.matchElement(bar)` and `expect(foo).to.containMatchingElement(bar)` though.

**Comment by ayrton** [comment]
Euh my bad - updated example

**Comment by benjamine** [comment]
maybe `expect(foo).to.contain.matchingElement(bar)` ? (following the dot-notation style of other assertions like 'have`)

**Comment by sherwinyu** [comment]
This would be great! If no one is working on it, I may try to take a stab at it this weekend -- came looking for this feature and found this existing issue.

**Comment by ayrton** [comment]
@sherwinyu feel free to start an implementation, this is def. something we will accept as a PR. I currently like @benjamine's suggestion the most

**Comment by Drasky-Vanderhoff** [comment]
I'm new to enzyme and i just found that really want to use containMatchingElement in order to avoid restriction of getting exactly the same tag with all attributes in order to match with the one i expecting. Glad that you are considering this feature, is there any idea of when this will be implemented or someone is actually working on it ? Thanks!

**Comment by ayrton** [comment]
@Drasky-Vanderhoff no work has been started as far as I know
