### ISSUE TITLE
expect(wrapper).to.contain() doesn't work for dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by Darkmap** [producthunt/chai-enzyme#89]
For this problem, I've tested both shallow and mount, the `expect(wrapper).to.contain()` cannot detect the rendered element from dangerouslySetInnerHTML.

For example, if I have a component like that:
```js
return (
            <div>
                <p dangerouslySetInnerHTML={{ __html: `<a href="fake link">click it</a>` }} />
            </div>
        )```
The test: `expect(wrapper).to.contain(<a href="fake link">click it</a>);` cannot pass.

**Comment by ljharb** [comment]
In that case you're seeing if it contains a ReactElement matching that `<a>`, which it does not.

If you set HTML, you have to search for *html* - ie, strings, not elements.

**Comment by Darkmap** [comment]
Really helpful, thank you!
Seems I just misunderstood the implementation of `dangerouslySetInnerHTML`.
