### ISSUE TITLE
Type assertion

### ISSUE THREAD

**Issue by marcodejongh** [producthunt/chai-enzyme#9]
Currently there is no way of asserting that a certain wrapper is a of a certain type.
So when asserting on type I have to resort to doing this:

```
expect(wrapper.type()).to.equal(SomeComponent);
```

Ideally I would think the assertion should look like this:

```
expect(wrapper).to.be.of.type(SomeComponent);
```

OR

```
expect(wrapper).to.have.type(SomeComponent);
```

Any thoughts? I will try to implement this tomorrow, taking any opinions voiced in this issue into consideration.

**Comment by ljharb** [comment]
`to.have.type` seems simplest to me. This seems like a reasonable addition.

**Comment by marcodejongh** [comment]
@ljharb I'll turn that in to a seperate story and close this one

**Comment by vesln** [comment]
both syntaxes should be doable if u add a `type` assertion, pr very welcome

**Comment by ayrton** [comment]
This been a part of chai-enzyme since [0.6.0](https://github.com/producthunt/chai-enzyme#typefunc).
